CREATE DATABASE customer_behavior;
USE customer_behavior;

-- Q1. What is the total revenue generated by male vs. female customers?
 
SELECT `Gender`,
       SUM(`Purchase_Amount_(USD)`) AS revenue
FROM customer
GROUP BY `Gender`;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT `Customer_ID`, `Purchase_Amount_(USD)`
FROM customer
WHERE `Discount_Applied` = 'Yes'
  AND `Purchase_Amount_(USD)` >= (
      SELECT AVG(`Purchase_Amount_(USD)`) FROM customer
  );

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT `Item_Purchased`,
       ROUND(AVG(`Review_Rating`), 2) AS `Average_Product_Rating`
FROM customer
GROUP BY `Item_Purchased`
ORDER BY AVG(`Review_Rating`) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT `Shipping_Type`,
       ROUND(AVG(`Purchase_Amount_(USD)`), 2) AS avg_purchase
FROM customer
WHERE `Shipping_Type` IN ('Standard', 'Express')
GROUP BY `Shipping_Type`;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT `Subscription_Status`,
       COUNT(`Customer_ID`) AS total_customers,
       ROUND(AVG(`Purchase_Amount_(USD)`),2) AS avg_spend,
       ROUND(SUM(`Purchase_Amount_(USD)`),2) AS total_revenue
FROM customer
GROUP BY `Subscription_Status`
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT `Item_Purchased`,
       ROUND(
         100.0 * SUM(CASE WHEN `Discount_Applied` = 'Yes' THEN 1 ELSE 0 END)
         / COUNT(*), 2
       ) AS discount_rate
FROM customer
GROUP BY `Item_Purchased`
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
    SELECT `Customer_ID`,
           `Previous_Purchases`,
           CASE
             WHEN `Previous_Purchases` = 1 THEN 'New'
             WHEN `Previous_Purchases` BETWEEN 2 AND 10 THEN 'Returning'
             ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS `Number of Customers`
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT `Category`,
           `Item_Purchased`,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (
             PARTITION BY `Category`
             ORDER BY COUNT(*) DESC
           ) AS item_rank
    FROM customer
    GROUP BY `Category`, `Item_Purchased`
)
SELECT item_rank, `Category`, `Item_Purchased`, total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT `Subscription_Status`,
       COUNT(`Customer_ID`) AS repeat_buyers
FROM customer
WHERE `Previous_Purchases` > 5
GROUP BY `Subscription_Status`;


-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
       SUM(`Purchase_Amount_(USD)`) AS total_revenue
FROM (
    SELECT
      CASE
        WHEN `Age` < 25 THEN 'Under 25'
        WHEN `Age` BETWEEN 25 AND 34 THEN '25-34'
        WHEN `Age` BETWEEN 35 AND 44 THEN '35-44'
        WHEN `Age` BETWEEN 45 AND 54 THEN '45-54'
        ELSE '55+'
      END AS age_group,
      `Purchase_Amount_(USD)`
    FROM customer
) t
GROUP BY age_group
ORDER BY total_revenue DESC;
